### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by anneloppe** [cfcurtis/sewingutils#25]
![PDFstitcherscripterror](https://user-images.githubusercontent.com/77735292/105183778-dc71c980-5b2e-11eb-8bc9-2ca546c3bbca.png)

I found an error, I think. My cousin wrote me that she couldn't get PDF Stitcher to work. I tried the newest version and I couldn't get it to work either. I run the .exe and allow SmartScreen to run it and then the error in the picture pops up. I tried the older one I had on my computer and it worked. I then tried going back through the versions and found that beta1 works and beta2 and versions after that gives the script error. 

We live in Denmark - perhaps it is a "local problem". 

Thank you for all your work on this, it's an amazing tool.

**Comment by cfcurtis** [comment]
Thank you for letting me know, it is odd that it runs beta1 but not beta2 as not much changed between the two. Can you run through the command prompt to see if it tells you more information about the error? It's not totally straightforward but I found [these instructions](https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt) that might help.

**Comment by cfcurtis** [comment]
Thanks for your patience Anne, I'm sorry that wasn't more useful output. I switched my system to Danish and managed to figure out what was going on, so I think I've fixed it now. It's a very small change so I just updated the original exe at https://github.com/cfcurtis/sewingutils/releases/download/v0.3/pdfstitcher.exe. I hope this one works for you, happy sewing :)

**Comment by anneloppe** [comment]
Hi! It works! Thanks a bunch, you sure are efficient! :-)  /Anne

**Comment by cfcurtis** [comment]
Great! I think I was too efficient though, I introduced another bug that makes it not actually generate a PDF. I updated again and it should fully work now (my bad for not making a new release).
